Create concert from tilbud
anders-hopland/informatikk-prosjekt pull request #95
Opened 2017-10-30 17:50 UTC by anders-hopland

2017-10-30 18:59 UTC, hehug7 requested changes

2017-10-30 18:59 UTC, hehug7 commented on mysite/app/templates/app/godkjenn_tilbud_manager.html
> +    <h1>Godkjenn tilbud</h1>
Har ikke testet denne koden, men det ser bra ut.

2017-10-30 18:59 UTC, hehug7 commented on mysite/app/templates/app/godkjenn_tilbud_manager.html
> +    <center>
Denne måtene å bruke en form er ikke helt bra. Bedre å putte formen i en div og bruke de samme klassene og html struktur. Ikke fan av `<center>`. Se om du finner det jeg har gjort på andre forms som er helt lik denne og prøv å gjennomfør det samme slik at vi eventuelt får klasser og liknende med på kjøpet.

2017-10-30 18:59 UTC, hehug7 commented on mysite/app/templates/app/godkjenn_tilbud_manager.html
> +    <br>
Dette er ikke noe vi bruker i html. Greit hvis man absolutt skal ha en quickfix, men det gjelder `<p>`, men igjen så brukes ikke dette generelt. Så skal du ha mer mellomrom så fjerner du dette og bruker css (såkalt `margin`).

2017-10-30 18:59 UTC, hehug7 commented on mysite/app/templates/app/tilbud_liste_manager.html
> +                        <td><a href="{% url 'godkjenn_tilbud_manager' tilbud.id %}" class="info-button">Se detaljer</a></td>
newlines...

2017-10-30 18:59 UTC, hehug7 commented on mysite/app/views.py
> +def godkjenn_tilbud_manager(request, artist, tilbud_id):
Ser bra ut, men får ikke testet koden.

2017-11-01 07:49 UTC, hehug7 requested changes
Jeg foretrekker å endre på det ferdiglagde skjemaet på "lag_tilbud.html" ved å legge til attributter slik at man ikke kan skrive tekst i dato eller prisfeltet.

Få også med en feilmelding/riktigmelding hvis det ble eller ikke ble registrert

2017-11-01 12:01 UTC, anders-hopland commented
Legge til success melding ved registrering må vente litt, må legge til django messages isåfall, noe som ikke har førstepri

2017-11-01 14:32 UTC, hehug7 commented
lag det på backloggen og evt en issue på github for varsel for registrert melding. Kanskje javascript kan bistå da? Det er snakk om en onsubmit = alert("registrert")

2017-11-01 14:38 UTC, anders-hopland commented
Kan ta i bruk django sine messages, da får du med error/syccess i fancy format. Tar det når rapporten ligger greit i rute :)

2017-11-01 14:42 UTC, hehug7 requested changes
Bra jobba. Er fortsatt noen ting som må gjøres.

2017-11-01 14:42 UTC, hehug7 commented on mysite/app/templates/app/tilbud_liste_manager.html
> +    <div class="space_around">
Litt mange elementer kanskje, men det er greit nok siden vi slipper å style samme elementer på flere sider (som kan føre til feil style på andre sider).
Ser at du ikke følger naming-konvensjonen i css.
Css klasser skrives igjen på formen: "space-around"

2017-11-01 14:42 UTC, hehug7 commented on mysite/app/templates/app/tilbud_liste_manager.html
> +    <div id="overview" class="page-content">
id skal bort etter refaktoreringen.

2017-11-01 14:42 UTC, hehug7 commented on mysite/app/templates/app/tilbud_liste_manager.html
> +            <tbody id="tableBdy">
Denne id-en skal også bort.

2017-11-01 14:42 UTC, hehug7 commented on mysite/app/templates/app/tilbud_liste_manager.html
> +        {% if antall_tilbud > 0 %}
Denne bruker du i stedet for de to id-ene og alt innenfor denne skal vel ha en indent?

Her kan du lære av hva jeg har gjort på det andre siden jeg tror at du skal kunne skrive:
`if tilbud.artist.all`

2017-11-01 14:42 UTC, hehug7 commented on mysite/app/templates/app/tilbud_liste_manager.html
> +                        <td><a href="{% url 'godkjenn_tilbud_bookingsjef' tilbud.id %}" class="info-button">Se detaljer</a></td>
Egentlig er kravet maks 90 tegn per linje (inkludert spaces), men jeg er ikke like nøye i dette prosjektet.
Når du har så lange linjer så kan du kjøre newlines uansett.

2017-11-01 14:44 UTC, anders-hopland commented on mysite/app/templates/app/tilbud_liste_manager.html
> +    <div class="space_around">
space-around fikset. Beholder divs

2017-11-01 14:52 UTC, hehug7 requested changes
Mangler en tabell som viser alle tilbud der det i siste kolonne står "godkjent" i grønn skrivt eller "ikke godkjent" i rødt eller "ubehandlet" uten farge hvis den er sendt men ikke blitt vurdert enda.

2017-11-02 09:00 UTC, hehug7 commented
TODO:
- Implementere dynamisk innlegging av konsert når manager godkjenner. 
- Error message på lag tilbud
- bs sin tabell

2017-11-06 08:32 UTC, anders-hopland commented
Bare radiobuttons på mailbox som mangler no :)

2017-11-06 12:55 UTC, hehug7 approved these changes

2017-11-06 12:55 UTC, merged