Feat 73 ba band info
anders-hopland/informatikk-prosjekt pull request #96
Opened 2017-10-31 12:54 UTC by marianvs

2017-10-31 13:27 UTC, hehug7 requested changes
Mye bra arbeid, men jeg vil teste det før jeg godkjenner

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/models.py
> +    band = models.CharField(max_length=500)
kjipt at vi fortsatt bruker norske navn på variabler i koden, men siden jeg ser at det har blitt brukt på andre steder lar vi det være.

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/static/css/base.css
> +    width: 100vw;
Bra innsats å sortere css, men ikke et must.

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/static/css/base.css
> +    margin: 1em 0 2em 0;
Bra at du bruker `em`

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/static/css/base.css
> +.previous_bands_btn{
Feil navnekonvensjon.
id: `detteErEnId`
klasse: `dette-er-en-class`

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/static/css/base.css
> +#previous_bands{
Med mindre du bruker denne iden til javascriptlogikk så endrer du dette til en klasse.
Her har du også brutt navnekonvensjon der id er beskrevet over. Hvis du ender opp med å endre dette til en klasse så bruker du bindestrek mellom ordene.

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/static/css/base.css
> +#previous_band_details{
samme som over

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/static/css/base.css
> +#previous_band_details > th, td{
samme som over

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/templates/app/bandSearch.html
> +        {% if bandInfo %}
Dette her var en veldig god løsning. Denne må vi andre hente fra.

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/templates/app/konsert.html
> +            <h3>Rigge team:</h3>
Bra gjort.

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/templates/app/tidligere_band.html
> +                <td><a href="{{ concert.band_detaljer_url }}" class="previous_bands_btn">{{ concert.artist.navn }}</a></td>
Lag new lines.
`<td>`
`<a>`
`innhold` osv...

2017-10-31 13:27 UTC, hehug7 commented on mysite/app/templates/head.html
> +            <img title="Home screen" id="logoImg" src="{% static "../static/images/logo.png" %}">
BRA!

2017-10-31 14:08 UTC, marianvs commented on mysite/app/models.py
> +    band = models.CharField(max_length=500)
Er ikke akkurat noe annet man kan kalle det da, med tanke på at det er et engelsk ord som norske har adoptert.

2017-10-31 14:11 UTC, marianvs commented on mysite/app/templates/app/bandSearch.html
> +        {% if bandInfo %}
Er faktisk ikke sikker på om dette vil funke på de andre, denne måten er basert på det faktumet at det ikke skal vises noe før man har søkt etter noe, så det blir litt andre variabler med i det, men er jo så klart bare å prøve.

2017-10-31 14:21 UTC, marianvs commented
Eneste som mangler er egentlig en liten ting som jeg ikke var helt sikker på hvordan jeg skulle gjøre. På tidligere_band siden, hvis et band er registrert som å ha hatt flere tidligere konserter, da vil det dukke opp en knapp for hver av de konsertene. Og når man går inn på detaljene til hver individuell konsert blir man ikke vist mer enn den ene, og den informasjonen som ble registrert den gangen. Så hvis Green Day har spilt i 2011 og 2014 vil det være en knapp til hver av dem og man får ikke infoen fra den andre uten å gå ut av den første, så over.
Det er nok ikke krise hvis det ikke blir fikset, men vi får vel se på det hvis det er behov/tid. Hvis noen enten klarer å fikse det, eller kan styre meg mot en løsning så kan jeg få fikset det greit nok, men som det er nå så vet jeg ikke hvordan.

2017-10-31 19:48 UTC, hehug7 commented on mysite/app/models.py
> +    band = models.CharField(max_length=500)
Nei akkurat band er jo greit nok, men feks: rigging, tilskuertall, inntektern nokkelInfo osv.

2017-10-31 19:51 UTC, hehug7 commented on mysite/app/templates/app/bandSearch.html
> +        {% if bandInfo %}
Det var helt genialt. Selvfølgelig må man anvende denne metoden riktig, men dette kommer med i refaktoreringen av oversiktstabellene.

2017-10-31 19:53 UTC, hehug7 commented
Jeg tenker at hvis det er noe som er feil, men som i utgangspunktet ikke lager feilmeldinger eller kræsjer serveren så lager du heller en issue på github og på backloggen slik at vi kan se på det som en egen fix.

2017-10-31 20:40 UTC, hehug7 requested changes
På tidligere band har du ikke en ordentlig tabell. Jeg ser du først har en " tabell " og deretter en detaljeside, men siden det egentlig ikke vises som en detaljeside så kan du gjøre det litt enklere å bare ha samme struktur bare at det du søker på vises på samme side med all infoen som står på detaljesiden.

Jeg sier dette nå fordi kunden vil klage på dette designet og "for mange klikk"

EDIT: Bra du har endret tabellen. Nå ser det bedre ut.

2017-10-31 20:42 UTC, hehug7 requested changes
Med mindre du bruker id-ene som jeg ser i cssen til noe logikk, så råder jeg deg til å endre disse til klasser og legge klasser inn som attributter i tagsa. Både for gjenbrukens skyld og for konvensjonen.

EDIT: Bra at du endret det så fort.

2017-11-01 05:28 UTC, marianvs commented
La til den siste commit når jeg så at alle sidene sine oversikter viste alle konsertene, samme hvilket år de spilles i.

2017-11-01 09:27 UTC, hehug7 approved these changes

2017-11-01 09:27 UTC, hehug7 commented
For et godt stykke arbeid.

2017-11-01 09:27 UTC, merged